name: Build Minecraft Client

on: [push, pull_request]

env:
  # Вот эта строчка уберет предупреждение и заставит всё работать на Node 24
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Или какая у тебя версия для Fabric 1.21.4
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build
